### ISSUE TITLE
IOError in Adafruit_I2C.py

### ISSUE THREAD

**Issue by lazamar** [gooligumelec/Joey-support-Python-code#1]
Hi, I am getting the following error when trying to run any of the examples in the github repository:

```
pi@ohm:~/Programs/Joey-support-Python-code$ python3 text_demo.py
Traceback (most recent call last):
  File "text_demo.py", line 14, in <module>
    display = joeyBoard()
  File "/home/pi/Programs/Joey-support-Python-code/joey_support.py", line 44, in __init__
    self.disp = HT16K33(address=address, debug=debug)
  File "/home/pi/Programs/Joey-support-Python-code/HT16K33.py", line 43, in __init__
    self.i2c = Adafruit_I2C(address)
  File "/home/pi/Programs/Joey-support-Python-code/Adafruit_I2C.py", line 43, in __init__
    self.bus = smbus.SMBus(busnum if busnum >= 0 else Adafruit_I2C.getPiI2CBusNumber())
IOError: [Errno 2] No such file or directory
```

I already installed everything needed. Is this a common error?

**Comment by gooligumelec** [comment]
It looks like I2C isn’t enabled on your Pi.
